### ISSUE TITLE
multiple dependencies

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/warden#29]
```
dependencies:
  - source: node_modules
    bundle: true
    main: bin/static/main.js
    files:
      - 'bootstrap/dist/js/bootstrap.min.js'
      - 'poppyjs/dist/Poppy.min.js'
      - "material-icons/iconfont/material-icons-outlined.woff2"
      - "material-icons/iconfont/material-icons-outlined.woff"
  - source: node_modules
    bundle: true
    main: bin/static/main.js
    files:
      - 'bootstrap/dist/js/bootstrap.min.js'
      - 'poppyjs/dist/Poppy.min.js'
      - "material-icons/iconfont/material-icons-outlined.woff2"
      - "material-icons/iconfont/material-icons-outlined.woff"
 ```
